[project]
name = "patari"
dynamic = ["version"]
description = "Analysis tool for clinical PA studies based on PATATO and NAPARI"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Moritz Schillinger"},
  {email = "moritz.schillinger@fau.de"},
]
classifiers = [
    "Framework :: napari",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
]
requires-python = ">=3.10"
# napari can be included in dependencies if napari imports are required.
# However, you should not include napari[all], napari[qt],
# or any other Qt bindings directly (e.g. PyQt5, PySide2).
# See best practices: https://napari.org/stable/plugins/building_a_plugin/best_practices.html
dependencies = [
    "numpy",
    "pandas",
    "magicgui",
    "qtpy",
    "imageio",
    "pyqtgraph",
    "scikit-image",
    "opencv-python-headless",
    "nibabel",
    "patato @ git+https://github.com/Mo-Sc/patato.git@e8b415f96a14e27b644c3e65afd4f58b24a18738",
    "openpyxl",
]

[project.optional-dependencies]
# Allow easily installation with the full, default napari installation
# (including Qt backend) using patari[all].
all = ["napari[all]"]

[project.entry-points."napari.manifest"]
patari = "patari:napari.yaml"



[build-system]
requires = ["setuptools>=42.0.0", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"patari" = ["*.yaml", "data/*.json"]

[tool.setuptools_scm]
write_to = "src/patari/_version.py"
fallback_version = "0.0.1+nogit"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
# filterwarnings = ["error"]  # recommended by PP309; deprecation warnings cause failures so leaving for the user to enable if desired
log_cli_level = "INFO"
testpaths = ["tests"]

[tool.black]
line-length = 79
target-version = ['py310', 'py311', 'py312', 'py313']
