[project]
name = "patari"
dynamic = ["version"]
description = "Analysis tool for clinical PA studies based on PATATO and NAPARI"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Moritz Schillinger"},
  {email = "moritz.schillinger@fau.de"},
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]
requires-python = ">=3.12"
dependencies = [
    "napari==0.8.0",
    "PyQt6==6.10.2",
    "numpy==2.4.6",
    "pandas==3.0.5",
    "magicgui==0.10.2",
    "qtpy==2.4.3",
    "imageio==2.37.4",
    "pyqtgraph==0.14.0",
    "scikit-image==0.26.0",
    "opencv-python-headless==5.0.0.93",
    "onnxruntime==1.28.0",
    "jax[cpu]>=0.4.13",
    "openpyxl==3.1.5",
    "patato @ https://github.com/Mo-Sc/patato/releases/download/patari-v0.5/patato-0.7.1.dev1+g517d19146-cp312-cp312-win_amd64.whl ; sys_platform == 'win32'",
    "patato @ https://github.com/Mo-Sc/patato/releases/download/patari-v0.5/patato-0.7.1.dev1+g517d19146-cp312-cp312-macosx_11_0_arm64.whl ; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "patato @ https://github.com/Mo-Sc/patato/releases/download/patari-v0.5/patato-0.7.1.dev1+g517d19146-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl ; sys_platform == 'linux'",
]

[project.optional-dependencies]
docs = [
    "mkdocs-material>=9.5",
    "mkdocstrings[python]>=0.25",
]

[project.gui-scripts]
patari = "patari.launcher:main"

[build-system]
requires = ["setuptools>=68", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"patari" = ["config/default_configs/*.json", "config/default_configs/**/*.json", "config/startup.png", "config/logo.png"]

[tool.setuptools_scm]
write_to = "src/patari/_version.py"
fallback_version = "0.0.1+nogit"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
log_cli_level = "INFO"
testpaths = ["tests"]

[tool.black]
line-length = 79
target-version = ['py310', 'py311', 'py312', 'py313']